---
version: "2.1"
services:
  prusaslicer-novnc:
    image: mikeah/prusaslicer-novnc
    container_name: prusaslicer-novnc
    environment:
      - SSL_CERT_FILE=/etc/ssl/certs/ca-certificates.crt
      - NVIDIA_VISIBLE_DEVICES=0
      - NVIDIA_DRIVER_CAPABILITIES=all
      - DISPLAY=:1
      - VNC_RESOLUTION=1900x1080
    volumes:
      - ./prints:/prints/
      - ./data:/configs/
    network_mode: host # THIS IS NEEDED FOR VIRTUALGL IMPORTANT, haven'tt figured out how to remove this yet
    restart: unless-stopped
